website/music/urls.py
from django.conf.urls import url
from .import views
app_name='music'
urlpatterns=[


    url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'^index$', views.IndexView.as_view(), name="index"),
    url(r'^search/$', views.Search.as_view(), name="search"),
    url(r'^register/$',views.UserFormView.as_view(),name='register'),
    url(r'(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    url(r'album/add/$',views.AlbumCreate.as_view(),name='album_add'),
    url(r'^songs/$', views.SongView.as_view(), name='songs'),
    url(r'^songs/add/$', views.SongaddView.as_view(), name='songadd'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),

]

website/website/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/',include('music.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/music/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Album(models.Model):
    artist=models.CharField(max_length=250)
    album_title=models.CharField(max_length=500)
    genre=models.CharField(max_length=100)
    album_logo=models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail',kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title+'-'+self.artist

class Song(models.Model):
    album=models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type=models.CharField(max_length=10)
    song_title=models.CharField(max_length=250)
    is_favorite=models.BooleanField(default=True)
    def __str__(self):
        return self.song_title

website/music/forms.py
from django.contrib.auth.models import User
from django import forms

from music.models import Song


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model=User
        fields=['username','email','password']

class SongForm(forms.ModelForm):


    class Meta:
        model=Song
        fields = ['song_title', 'file_type', 'is_favorite']


class LoginForm(forms.Form):
    username=forms.CharField(max_length=300)
    password=forms.CharField(widget=forms.PasswordInput)





            #        def clean(self):
 #           form_data = self.cleaned_data
          #  if form_data['password'] != form_data['password_repeat']:
           #     self._errors["password"] = ["Password do not match"]  # Will raise a error message
            #    del form_data['password']
           # return form_data

website/music/views.py
from django.views import generic
from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic.edit import CreateView
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login, logout
from .models import Album,Song
from django.views.generic import View
from .forms import UserForm, LoginForm


class HomeView(generic.TemplateView):
    template_name = 'music/home.html'


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class SongView(generic.ListView):
    template_name = 'music/songs.html'
    context_object_name = 'all_songs'

    def get_queryset(self):
        return Song.objects.all()

class SongaddView(CreateView,):
    template_name = 'music/addsong.html'
    model=Song
    fields=['song_title','file_type','is_favorite','album']
    def get_success_url(self):
        return '/music/index'


class ContactView(generic.TemplateView):
    template_name='music/contact.html'


class LogoutView(generic.TemplateView):
    template_name = 'music/logout.html'


class DetailView(generic.DetailView):
    model=Album
    template_name='music/detail.html'

class AlbumCreate(CreateView):
    model=Album
    fields=['artist','album_title','genre','album_logo']

class UserFormView(View):
    form_class= UserForm
    template_name='music/registration_form.html'

    def get(self,request):
        form=self.form_class()
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)


        if form.is_valid():
            user=form.save(commit=False)


            #cleaned (normalised data)

            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #returns user objects if credentials are correct
            user=authenticate(username=username,password=password)

            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect('music:index')
        return render(request,self.template_name,{'form':form})

class LoginView(View):
    form_class= LoginForm
    template_name='music/registration_form.html'

    def get(self,request):
        form=self.form_class()
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)

        if form.is_valid():
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']

            user=authenticate(username=username,password=password)

            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect('music:index')
        return render(request,self.template_name,{'form':form})

class Search(generic.ListView):
    model = Album
    template_name = 'music/search.html'
    context_object_name = 'search_list'

    def get_queryset(self):
        print self.request.GET
        query = self.request.GET["q"]
        return self.model.objects.filter(album_title__icontains=query)

website/music/templates/music/addsong.html
{% extends 'music/base.html' %}
{% block title %} Add a New song {% endblock %}
{% block albums_active %} active {% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizantal"  method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success" >submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
    </div>
    </div>
</div>

{% endblock %}

website/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %} Add a New Album {% endblock %}
{% block albums_active %} active {% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizantal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success" >submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
    </div>
    </div>
</div>

{% endblock %}

website/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>viberr</title>
    {% load staticfiles %}
    <link rel= "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel= "stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
  <nav class="navbar  navbar-inverse">
    <div class="container-fluid">
        <!__logo__>
        <div class="navbar-header">
            <button type="button"  class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">viberr</a>
         </div>

        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">

                <li class="active">
                    <a href ="{%url 'music:index' %}">
                        <span class="glyphicon  glyphicon-cd"  aria-hidden="true"></span>&nbsp;
                        Albums
                     </a>

                <li class="">
                    <a href ="{%url 'music:songs'%}">
                        <span class="glyphicon  glyphicon-music"  aria-hidden="true"></span>&nbsp;
                        Songs
                     </a>

                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:search'%}">{%csrf_token%}
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">search</button>
            </form>

             <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:contact' %}">
                        <span class="glyphicon  glyphicon-earphone"  aria-hidden="true"></span>&nbsp;contact
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album_add' %}">
                        <span class="glyphicon  glyphicon-plus"  aria-hidden="true"></span>&nbsp;Add Album
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{%url 'music:logout'%}">
                        <span class="glyphicon  glyphicon-off"  aria-hidden="true"></span>&nbsp;logout
                    </a>
                </li>
            </ul>


        </div>


    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

website/music/templates/music/contact.html
{% extends 'music/base.html' %}
{% block body %}
    <h1>p.siva prasanna</h1>
    <h3>
        Email:sivaprasanna69@gmail.com</br>
        mobile:7661980314</br>
    </h3>

{% endblock %}

website/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}
    <img src="{{ album.album_logo.url }}" style="width: 250px;">

    <h1>{{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>

        {% for song in album.song_set.all %}
            {{song.song_title}}
            {% if song.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png"/>
            {% endif %}
            <br>
        {% endfor %}
    </br>
    <form action="{%url 'music:songadd'%}">
    <input type="submit" value="Add song" />
    </form>



{% endblock %}

website/music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{field}}</div>
    </div>
{% endfor %}

website/music/templates/music/home.html
{% load staticfiles %}

<html>
<head>

    <link rel="stylesheet" href="{% static 'music/home.css' %}">
    <title>Viberrr</title>
    <a class="navbar-brand" href="{% url 'music:login' %}">login</a></br>
    <a class="navbar-brand" href="{% url 'music:register' %}">register</a>
</head>

<body>
<h1>viberrr</h1>
</body>

</html>

website/music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}

    {%if all_albums%}
    <ul>
        <h1>Here are the list of albums:</h1>
        {%for album in all_albums%}
        <li>
            <a href="{% url 'music:detail' album.id %} "> {{album.album_title}} </a>
        </li>
        {%endfor%}
    </ul>
    {%else%}
       <h3>you don't have any albums</h3>
    {%endif%}
{% endblock %}

website/music/templates/music/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>viberr</title>
    {% load staticfiles %}
    <link rel= "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel= "stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
  <nav class="navbar  navbar-inverse">
    <div class="container-fluid">
        <!__logo__>
        <div class="navbar-header">
            <button type="button"  class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">viberr</a>
         </div>

        <div class="collapse navbar-collapse" id="topNavBar">
{% block title %} login {% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizantal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success" >submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
    </div>
    </div>
</div>

{% endblock %}

website/music/templates/music/logout.html
{% load staticfiles %}
<h1> Thank you for spending your quality time</h1>
<a class="nav-link" href="{% url 'music:home' %}">click here to relogin</a></br>

website/music/templates/music/registration_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>viberr</title>
    {% load staticfiles %}
    <link rel= "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel= "stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
  <nav class="navbar  navbar-inverse">
    <div class="container-fluid">
        <!__logo__>
        <div class="navbar-header">
            <button type="button"  class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">viberr</a>
         </div>

        <div class="collapse navbar-collapse" id="topNavBar">
{% block title %} Register {% endblock %}
{% block albums_active %} active {% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizantal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success" >submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
    </div>
    </div>
</div>

{% endblock %}

website/music/templates/music/search.html
{% extends 'music/base.html' %}
{% block body %}

    {%if search_list%}
    <ul>
        <h1>search found:</h1>
        {%for album in search_list%}
        <a href="{% url 'music:detail' album.id %} "> {{album.album_title}} </a>
        {%endfor%}
    </ul>
    {%else%}
       <h3>you don't have any search item</h3>
    {%endif%}
{% endblock %}

website/music/templates/music/songs.html
{% extends 'music/base.html' %}
{% block body %}

    {%if all_songs%}
    <ul>

        {%for song in all_songs%}

                <li>
                    {{song.song_title}}
                </li>


        {%endfor%}
    </ul>
    {%else%}
       <h3>you don't have any songs</h3>
    {%endif%}
{% endblock %}